export const brandList = [
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 5,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 6,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 7,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 8,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 10,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 12,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 11,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 9,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
];
export const manList = [
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 5,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 6,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 7,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 8,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 10,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 9,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 12,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 11,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },

];
export const saleList = [
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 5,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 6,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 7,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 8,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
];
export const womanList = [
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 5,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 6,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 7,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 8,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
 
];
export const trendingList = [
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
  {
    id: 1,
    image: "/images/t1.jpeg",
    price: "1",
    description: "Product Description 1",
    buttonText: "View Details",
  },
  {
    id: 2,
    image: "/images/t2.jpeg",
    price: "2",
    description: "Product Description 2",
    buttonText: "View Details",
  },
  {
    id: 3,
    image: "/images/t3.jpeg",
    price: "3",
    description: "Product Description 3",
    buttonText: "View Details",
  },
  {
    id: 4,
    image: "/images/mureed.jpg",
    price: "4",
    description: "Product Description 4",
    buttonText: "View Details",
  },
];